server:
  port: 9001
  compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
        min-response-size: 1024
spring:
   application:
      name: DEPARTMENT-SERVICE
   zipkin:
      base-url: http://127.0.0.1:9411/

