server:
   port: 9191

spring: 
   application:
      name: API-GATEWAY
   cloud:
     gateway:
         routes:
            - id: DEPARTMENT-SERVICE
              uri: lb://DEPARTMENT-SERVICE
              predicates: 
                 - Path=/departments/**
            - id: EMPLOYEE-SERVICE
              uri: lb://EMPLOYEE-SERVICE
              predicates: 
                 - Path=/employee/**
management:
  endpoints:
    web:
      exposure:
        include: "*"