server:
   port: 9191

spring: 
   application:
      name: API-GATEWAY
   cloud:
      gateway:
         routes:
            - id: DEPARTMENT-SERVICE
              uri: lb://DEPARTMENT-SERVICE
              predicates: 
                 - Path=/departments/**
            - id: EMPLOYEE-SERVICE
              uri: lb://EMPLOYEE-SERVICE
              predicates: 
                 - Path=/employee/**
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url: 
        defaultZone: http://localhost:8761/eureka/
  instance: 
     hostname: localhost